images/config/routes.rb
Refinery::Application.routes.draw do
  match '/system/images/*dragonfly', :to => Dragonfly[:images]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :images, :except => :show do
      collection do
        get :insert
      end
    end
  end
end

images/app/models/image.rb
class Image < ActiveRecord::Base

  # What is the max image size a user can upload
  MAX_SIZE_IN_MB = 5

  image_accessor :image

  validates :image, :presence  => { :message => ::I18n.t('image_specify_for_upload') },
                    :length    => { :maximum => MAX_SIZE_IN_MB.megabytes,
                                    :message => ::I18n.t('image_should_be_smaller_than_max_image_size',
                                                         :max_image_size => MAX_SIZE_IN_MB.megabytes) }
  validates_property :mime_type, :of => :image, :in => %w(image/jpeg image/png image/gif),
                     :message => ::I18n.t('image_must_be_these_formats')

  # Docs for acts_as_indexed http://github.com/dougal/acts_as_indexed
  acts_as_indexed :fields => [:title]

  # when a dialog pops up with images, how many images per page should there be
  PAGES_PER_DIALOG = 18

  # when a dialog pops up with images, but that dialog has image resize options
  # how many images per page should there be
  PAGES_PER_DIALOG_THAT_HAS_SIZE_OPTIONS = 12

  # when listing images out in the admin area, how many images should show per page
  PAGES_PER_ADMIN_INDEX = 20

  delegate :size, :mime_type, :url, :width, :height, :to => :image

  class << self
    # How many images per page should be displayed?
    def per_page(dialog = false, has_size_options = false)
      if dialog
        unless has_size_options
          PAGES_PER_DIALOG
        else
          PAGES_PER_DIALOG_THAT_HAS_SIZE_OPTIONS
        end
      else
        PAGES_PER_ADMIN_INDEX
      end
    end

    def user_image_sizes
      RefinerySetting.find_or_set(:user_image_sizes, {
        :small => '110x110>',
        :medium => '225x255>',
        :large => '450x450>'
      })
    end
  end

  # Get a thumbnail job object given a geometry.
  def thumbnail(geometry = nil)
    if geometry.is_a?(Symbol) and self.class.user_image_sizes.keys.include?(geometry)
      geometry = sizes[geometry].presence
    end

    if geometry.present? && !geometry.is_a?(Symbol)
      self.image.thumb(geometry)
    else
      self.image
    end
  end

  # Returns a titleized version of the filename
  # my_file.jpg returns My File
  def title
    CGI::unescape(self.image_name.to_s).gsub(/\.\w+$/, '').titleize
  end

end

images/app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  include Admin::ImagesHelper

  crudify :image,
          :order => "created_at DESC",
          :sortable => false

  before_filter :change_list_mode_if_specified, :init_dialog

  def index
    search_all_images if searching?
    paginate_all_images

    if RefinerySetting.find_or_set(:group_images_by_date_uploaded, true)
      @grouped_images = group_by_date(@images)
    end
    render :layout =>'refinery/admin'
  end

  def new
    @image = Image.new if @image.nil?

    @url_override = admin_images_url(:dialog => from_dialog?)
  end

  # This renders the image insert dialog
  def insert
    self.new if @image.nil?

    @url_override = admin_images_url(:dialog => from_dialog?, :insert => true)

    if params[:conditions].present?
      extra_condition = params[:conditions].split(',')

      extra_condition[1] = true if extra_condition[1] == "true"
      extra_condition[1] = false if extra_condition[1] == "false"
      extra_condition[1] = nil if extra_condition[1] == "nil"
    end

    find_all_images(({extra_condition[0].to_sym => extra_condition[1]} if extra_condition.present?))
    search_all_images if searching?

    paginate_images

    render :action => "insert"
  end

  def create
    @images = []
    begin
      unless params[:image].present? and params[:image][:image].is_a?(Array)
        @images << (@image = Image.create(params[:image]))
      else
        params[:image][:image].each do |image|
          @images << (@image = Image.create(:image => image))
        end
      end
    rescue Dragonfly::FunctionManager::UnableToHandle
      logger.warn($!.message)
      @image = Image.new
    end

    unless params[:insert]
      if @images.all?{|i| i.valid?}
        flash.notice = t('refinery.crudify.created', :what => "'#{@images.collect{|i| i.title}.join("', '")}'")
        unless from_dialog?
          redirect_to :action => 'index'
        else
          render :text => "<script>parent.window.location = '#{admin_images_url}';</script>"
        end
      else
        self.new # important for dialogs
        render :action => 'new'
      end
    else
      if @images.all?{|i| i.valid?}
        @image_id = @image.id if @image.persisted?
        @image = nil
      end
      self.insert
    end
  end

protected

  def init_dialog
    @app_dialog = params[:app_dialog].present?
    @field = params[:field]
    @update_image = params[:update_image]
    @thumbnail = params[:thumbnail]
    @callback = params[:callback]
    @conditions = params[:conditions]
  end

  def paginate_images
    @images = @images.paginate(:page => (@paginate_page_number ||= params[:page]),
                               :per_page => Image.per_page(from_dialog?, !@app_dialog))
  end

  def restrict_controller
    super unless action_name == 'insert'
  end

  def store_current_location!
    super unless action_name == 'insert' or from_dialog?
  end

end

images/app/helpers/admin/images_helper.rb
  module Admin::ImagesHelper

    def image_views
      RefinerySetting.find_or_set(:image_views, [:grid, :list])
    end

    def current_image_view
      RefinerySetting.find_or_set(:preferred_image_view, :list)
    end

    def other_image_views
      image_views.reject {|image_view| image_view.to_s == current_image_view.to_s }
    end

    def change_list_mode_if_specified
      if action_name == 'index' and params[:view].present? and image_views.include?(params[:view].to_sym)
        RefinerySetting.set(:preferred_image_view, params[:view])
      end
    end

    def images_paginator(collection, dialog = false)
      will_paginate collection, :renderer => Refinery::LinkRenderer
    end

  end

images/app/views/admin/images/_existing_image.html.erb
<div id='existing_image_area' class='dialog_area' <%= "style='display:none;'" if @image.errors.any? %>>
  <%= render :partial => '/shared/admin/search',
             :locals => {:url => insert_admin_images_url(params.dup.delete(:image))} %>
  <input type='hidden' name='selected_image' id='selected_image' />
  <div id='existing_image_area_content' class='clearfix'>
<% if @images.any? %>
    <ul>
<%
      @images.each do |image|
        thumbnail_urls = {
          :"data-original" => image.url,
          :"data-grid" => image.thumbnail('135x135#c').url
        }
        ::Image.user_image_sizes.sort_by{|key,geometry| geometry}.each do |size, pixels|
          thumbnail_urls[:"data-#{size.to_s.parameterize}"] = image.thumbnail(pixels).url
        end
-%>
        <li<%= " class='selected'" if @image_id == image.id %>>
          <%= image_fu(image, '106x106#c', {
                         :alt => image.title,
                         :title => image.title,
                         :id => "image_#{image.id}",
                         :'data-id' => image.id
                       }.merge(thumbnail_urls)) -%>
        </li>
      <% end -%>
    </ul>
<% elsif searching? %>
    <%= t('shared.admin.search.no_results') %>
<% end %>
  </div>

  <%= images_paginator @images, from_dialog? %>

  <% unless @app_dialog or @images.empty? %>
    <div id='existing_image_size_area' class='clearfix'>
      <input type='hidden' name='selected_image_size' id='selected_image_size' />
      <p>
        <input type="checkbox" id="wants_to_resize_image" name="wants_to_resize_image" value="1" checked="checked" />
        <label for='wants_to_resize_image' class='stripped' style='font-weight: bold;'>
          <%= t('.resize_image') %>
        </label>
      </p>
      <ul>
        <%
          ::Image.user_image_sizes.sort_by { |key, geometry| geometry }.each_with_index do |(size, pixels), index|
            safe_pixels = pixels.to_s.gsub(/[<>=]/, '')
            # (parndt): ' selected' if size.to_s == 'medium' is not very generic, but I
            # can't think of a decent way of making it so for even sets (e.g. 2,4,6,8,etc image sizes).
        -%>
            <li id="image_dialog_size_<%= index %>" class="image_dialog_size<%= ' selected' if size.to_s == 'medium' %>">
              <%= link_to size.to_s, "##{size}",
                          :'data-geometry' => pixels,
                          :'data-size' => size.to_s.parameterize,
                          :title   => "#{size} image (#{safe_pixels})",
                          :tooltip => "#{size} image (#{safe_pixels})" %>
            </li>
        <% end -%>
      </ul>
    </div>
  <% end %>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => nil,
               :cancel_url => '',
               :submit_button_text => t('.button_text'),
               :hide_submit => @images.empty?,
               :hide_cancel => false,
               :hide_delete => true,
               :cancel_title => nil
             } if @app_dialog or @images.any? or searching? %>
</div>

images/app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image], :url => @url_override || @url, :html => {:multipart => true} do |f| %>

  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => @image,
               :include_object_name => false
             } %>

  <div class='field'>
    <% if action_name =~ /(edit)|(update)/ %>
      <p>
        <%= t('.use_current_image') %>
        <em><%= t('.or') %></em><%= t('.replace_image') %>
      </p>
      <p>
        <%= f.file_field :image %>
      </p>
    <% else %>
      <% # we must only hint at multiple when it's a new record otherwise update fails. %>
      <%= f.file_field :image, :multiple => true %>
    <% end %>
  </div>

  <div class='field'>
    <label><%= t('.maximum_image_size', :megabytes => Image::MAX_SIZE_IN_MB) %></label>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :hide_cancel => (@app_dialog or action_name == "insert" or from_dialog?),
               :delete_title => t('admin.images.delete'),
               :delete_confirmation => t('shared.admin.delete.message', :title => @image.image_name)
             } -%>

  <% if @app_dialog %>
    <input type='hidden' name='app_dialog' value='<%= @app_dialog %>' />
    <input type='hidden' name='field' value='<%= @field %>' />
    <input type='hidden' name='update_image' value='<%= @update_image %>' />
    <input type='hidden' name='thumbnail' value='<%= @thumbnail %>' />
    <input type='hidden' name='callback' value='<%= @callback %>' />
    <input type='hidden' name='conditions' value='<%= @conditions %>' />
  <% end %>
<% end %>

<% if action_name =~ /(edit)|(update)/ %>
  <div id='existing_image'>
    <label><%=t('.current_image') %></label>
    <%= image_fu @image, '225x255>', :class => "brown_border" %>
  </div>
<% end %>

images/app/views/admin/images/_grid_view.html.erb
<ul id="image_grid" class="clearfix">
  <% @images.each_with_index do |image, index| -%>
    <li id="image_<%= image.id %>" class='image_<%= index % 5 %>'>
      <%= image_fu image, '135x135#c', :title => image.title %>
      <span class='actions'>
        <%= link_to refinery_icon_tag('eye.png'), image.url,
                    :target => "_blank",
                    :title => t('.view_live_html') %>
        <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_image_path(image),
                    :title => t('admin.images.edit') %>
        <%= link_to refinery_icon_tag('delete.png'), admin_image_path(image),
                    :class => "cancel confirm-delete",
                    :title => t('admin.images.delete'),
                    :confirm => t('shared.admin.delete.message', :title => image.title),
                    :method => :delete %>
      </span>
    </li>
  <% end -%>
</ul>

images/app/views/admin/images/_list_view.html.erb
<% if RefinerySetting.find_or_set(:group_images_by_date_uploaded, true) %>
  <% @grouped_images.each do |container| %>
    <% date_time = (image_group = container.last).first.created_at %>
    <% date = Date.parse(date_time.to_s) %>
    <h3><%= l(date, :format => :long ) %></h3>
    <ul>
      <%= render :partial => 'list_view_image', :collection => image_group %>
    </ul>
  <% end %>
<% else %>
  <ul>
    <%= render :partial => 'list_view_image', :collection => @images %>
  </ul>
<% end %>

images/app/views/admin/images/_list_view_image.html.erb
<li id="sortable_<%= list_view_image.id %>" class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= list_view_image.title %> <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('eye.png'), list_view_image.url,
                :target => "_blank",
                :title => "#{image_fu list_view_image, '96x96#c', :size => '96x96'}" %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_image_path(list_view_image),
                :title => t('admin.images.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), admin_image_path(list_view_image),
                :class => "cancel confirm-delete",
                :title => t('admin.images.delete'),
                :confirm => t('shared.admin.delete.message', :title => list_view_image.title),
                :method => :delete %>
  </span>
</li>

images/app/views/admin/images/edit.html.erb
<%= render :partial => "form" %>

images/app/views/admin/images/index.html.erb
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% if @images.any? %>
    <%= will_paginate @images %>
    <%= render :partial => "#{current_image_view}_view" %>
    <%= will_paginate @images %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong>
          <%= t('.no_images_yet') %>
        </strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => admin_images_url} %>
    </li>
    <li>
      <%= link_to t('.create_new_image'), new_admin_image_url(:dialog => true, :width => 600, :height => 300),
                  :class => "add_icon" %>
    </li>
    <% other_image_views.each do |image_view| %>
      <li>
        <%= link_to t('.view.switch_to', :view_name => t(".view.#{image_view}")),
                    admin_images_url(:view => image_view, :page => params[:page]),
                    :class => "reorder_icon"  %>
      </li>
    <% end %>
  </ul>
</div>

images/app/views/admin/images/insert.html.erb
<% user_can_modify_images = ::Refinery::Plugins.active.names.include?("refinery_images") %>
<div id='dialog_menu_left'>
  <% if (any_images = @images.any?) or searching? %>
    <span id="existing_image_radio" class="radio<%= " selected_radio" if (no_errors = @image.errors.empty?) %>">
      <input type='radio' name='image_type' value='existing_image' id='image_type_existing'<%= " checked='true'" if no_errors or searching? %> />
      <label for='image_type_existing' class='stripped'><%=t('.existing_image')%></label>
    </span>
  <% end %>
  <% if user_can_modify_images %>
    <span id="upload_image_radio" class="radio<%= " selected_radio" if !no_errors and !any_images %>">
      <input type='radio' name='image_type' value='upload_image' id='image_type_upload'<%= " checked='true'" if (!any_images or !no_errors) and !searching? %> />
      <label for='image_type_upload' class='stripped'><%= t('.new_image') %></label>
    </span>
  <% end %>
</div>

<div id='dialog_main'>
  <% if any_images or user_can_modify_images %>
    <%= render :partial => "existing_image" if any_images or searching? %>

    <% if user_can_modify_images %>
      <div id='upload_image_area' class='dialog_area'<%= " style='display:none;'" if any_images and (no_errors or searching?) %>>
        <%= render :partial => "form", :locals => {:insert => true} %>
      </div>
    <% end %>
  <% else %>
    <% flash.now[:error] = t('admin.images.index.no_images_yet').split('.').first.html_safe + "." %>
    <%= render :partial => "/shared/admin/form_actions",
               :locals => {
                 :f => nil,
                 :cancel_url => '',
                 :hide_cancel => false,
                 :hide_delete => true,
                 :hide_submit => true,
                 :cancel_button_text => t('shared.admin.form_actions.close'),
                 :cancel_title => nil
               } %>
  <% end %>
</div>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      image_dialog.init(<%= @callback.present? ? "self.parent.#{@callback}" : "null" %>);
    });
  </script>
<% end %>

images/app/views/admin/images/new.html.erb
<%= render :partial => "/admin/images/form" %>