authentication/config/routes.rb
::Refinery::Application.routes.draw do

  # Add Devise necessary routes.
  # For Devise routes, see: https://github.com/plataformatec/devise
#  namespace :refinery do
#    devise_for :users,  :as => :registrations, :controllers => {
#      :sessions => 'sessions',
#      :registrations => 'registrations',
#      :passwords => 'passwords'
#    }, :path_names => {
#      :sign_out => 'logout',
#      :sign_in => 'login',
#      :sign_up => 'register'
#    }
#  end

  # Override Devise's default after login redirection route.  This will pushed a logged in user to the dashboard.
  get 'refinery', :to => 'admin/dashboard#index', :as => :refinery_root
  #get 'refinery', :to => 'admin/dashboard#index', :as => :admin_root

  # Override Devise's other routes for convenience methods.
  #get 'refinery/login', :to => "sessions#new", :as => :new_user_session
  #get 'refinery/login', :to => "sessions#new", :as => :refinery_login
  #get 'refinery/logout', :to => "sessions#destroy", :as => :destroy_user_session
  #get 'refinery/logout', :to => "sessions#destroy", :as => :logout

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :admins, :except => :show
  end

end

authentication/app/views/admin/admins/_form.html.erb
<%= form_for [:admin, @admin] do |f| %>

  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => @admin,
               :include_object_name => true
             } %>

  <div class='field'>
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>
  <div class='field'>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class='field'>
    <%= f.label :password %>
    <%= f.password_field :password, :autocomplete => 'off' %>
    <%= "<br /><span class='preview'>#{t('.blank_password_keeps_current')}</span>".html_safe if @user.persisted? %>
  </div>
  <div class='field'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :autocomplete => 'off' %>
  </div>
  <div class='field plugin_access'>
    <span class='label_with_help'>
      <%= f.label :plugin_access, nil, :class => "title_label" %>
      <%= link_to "(#{t('.enable_all')})", "", :id => "user_plugins_enable_all" %>
    </span>
    <ul id='plugins' class='checkboxes'>
      <% @available_plugins.each do |plugin| -%>
        <% if Refinery::Plugins.always_allowed.names.include?(plugin[:name]) or
              (plugin[:name] == 'refinery_users' and @user.id == current_user.id) %>
          <%= hidden_field_tag 'user[plugins][]', plugin[:name],
                               :id => "plugins_#{plugin[:name]}" %>
        <% else %>
          <li>
            <%= check_box_tag 'user[plugins][]', plugin[:name],
                              @selected_plugin_names.include?(plugin[:name]),
                              :id => "plugins_#{plugin[:name]}" %>
            <%= f.label 'user[plugins][]',
                        t("plugins.#{plugin[:name].downcase}.title", :default => plugin[:title]),
                        :class => "stripped",
                        :for => "plugins_#{plugin[:name]}" %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <% if current_user.has_role?(:superuser) and RefinerySetting.find_or_set(:superuser_can_assign_roles, false) %>
    <div class='field role_access'>
      <span class='label_with_help'>
        <%= f.label :role_access, nil, :class => "title_label" %>
      </span>
      <ul id='roles' class='checkboxes'>
        <% @available_roles.each do |role|
          downcased_title = (title = role[:title]).downcase -%>
          <li>
            <%= check_box_tag 'user[roles][]', downcased_title, @user.has_role?(title),
                              :id => "roles_#{downcased_title}" %>
            <%= f.label 'user[roles][]', t("roles.#{downcased_title}", :default => title),
                        :class => 'stripped',
                        :for => "roles_#{downcased_title}" %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :hide_delete => !current_user.can_delete?(@user),
               :delete_title => t('admin.users.delete'),
               :delete_confirmation => t('shared.admin.delete.message', :title => @user.username)
             } %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function() {
      $('#user_plugins_enable_all').click(function(e, a) {
        $('div.field.plugin_access ul#plugins li input:checkbox').attr('checked', true);
        e.preventDefault();
      });
    });
  </script>
<% end %>

authentication/app/views/admin/admins/_user.html.erb
<li id="sortable_<%= user.id %>" class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <strong><%= user.login %></strong>
    <span class="preview">
      <%= t('.preview', :who => user.email, :created_at => l(user.created_at, :format => :short)) %>
    </span>
  </span>
  <span class='actions'>
    <%= mail_to user.email, refinery_icon_tag('email_go.png'),
                :title => t('.email_user') %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_admin_path(user),
                :title => t('admin.users.edit')%>
    <%= link_to refinery_icon_tag('delete.png'), admin_admin_path(user),
                :class => "cancel confirm-delete",
                :title => t('admin.users.delete'),
                :method => :delete,
                :confirm => t('shared.admin.delete.message', :title => user.login) if current_admin.can_delete?(user) %>
  </span>
</li>

authentication/app/views/admin/admins/edit.html.erb
<%= render :partial => 'form' %>

authentication/app/views/admin/admins/index.html.erb
<div id='records'>
  <%= will_paginate @admins %>
  <ul>
    <%= render :partial => "user", :collection => @admins %>
  </ul>
  <%= will_paginate @admins %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= link_to t('.create_new_user'), new_admin_admin_url, :class => "add_icon" %>
    </li>
  </ul>
</div>

authentication/app/views/admin/admins/new.html.erb
<%= render :partial => "form" %>