pages/config/routes.rb
::Refinery::Application.routes.draw do
  get '/pages/:id', :to => 'pages#show', :as => :page, :constraints => {:id => /\w[0-9]+/}

  scope(:path => 'refinery', :as => 'admin',:module=>'admin') do
    resources :pages, :except => :show do
      collection do
        post :update_positions
      end
    end

    resources :pages_dialogs, :only => [] do
      collection do
        get :link_to
        get :test_url
        get :test_email
      end
    end

    resources :page_parts, :only => [:new, :create, :destroy]
  end
end

pages/app/controllers/admin/pages_dialogs_controller.rb
class Admin::PagesDialogsController < Admin::DialogsController

  require 'net/http'

  crudify :page

  def link_to
    @pages = Page.paginate :page => params[:page],
                           :conditions => {:parent_id => nil},
                           :order => 'position ASC',
                           :per_page => Page.per_page(dialog=true)

    @resources = Resource.paginate :page => params[:resource_page],
                                   :order => 'created_at DESC',
                                   :per_page => Resource.per_page(dialog=true)

    # web address link
    @web_address_text = "http://"
    @web_address_text = params[:current_link] if params[:current_link].present? and params[:current_link] =~ /^http:\/\//
    @web_address_target_blank = (params[:target_blank] == "true")

    # mailto link
    if params[:current_link].present?
      if params[:current_link] =~ /^mailto:/
        @email_address_text = params[:current_link].split("mailto:")[1].split('?')[0]
      end
      @email_default_subject_text = params[:current_link].split('?subject=')[1] || params[:subject]
      @email_default_body_text = params[:current_link].split('?body=')[1] || params[:body]
    end

    # resource link
    if params[:current_link].present?
      is_resource_link = params[:current_link].include?("/system/resources")
    end

    if params[:paginating].present?
      @page_area_selected = (params[:paginating] == "your_page")
      @resource_area_selected = (params[:paginating] == "resource_file")
    else
      @page_area_selected = (!is_resource_link and @web_address_text == "http://" and @email_address_text.blank?)
      @web_address_area_selected = (@web_address_text != "http://")
      @email_address_area_selected = @email_address_text.present?
      @resource_area_selected = is_resource_link
    end
  end

  def test_url
    unless params[:url].blank?
      url = URI.parse(params[:url])
      if url.host.nil? && params[:url].start_with?('/')
        url.host = URI.parse(request.url).host
      end

      http = Net::HTTP.new(url.host)
      request = Net::HTTP::Get.new(url.path.blank? ? "/" : url.path)

      response = http.request request

      render :json => {:result => case response
      when Net::HTTPSuccess, Net::HTTPRedirection
        'success'
      else
        'failure'
      end }
    end

    rescue
      render :json => {:result => 'failure'}
  end

  def test_email
    unless params[:email].blank?
      valid = params[:email] =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

      render :json => if valid
        {:result => 'success'}
      else
        {:result => 'failure'}
      end
    end
  end

end

pages/app/views/admin/pages_dialogs/_page_link.html.erb
<% linked = (url_for(page_link.url) == params[:current_link]) if params[:current_link].present? -%>
<li class='clearfix<%= " child#{child}" if child %><%= " linked" if linked%>' id="<%= dom_id(page_link) -%>">
  <%= link_to page_link.title_with_meta.html_safe, page_link.url,
              :title => t('.link_to_this_page'),
              :rel => page_link.title,
              :class => 'page_link' %>
</li>
<%= render :partial => 'page_link', :collection => page_link.children,
           :locals => {
             :child => (child ||= 0) + 1
           } if page_link.children.any? -%>

pages/app/views/admin/pages_dialogs/link_to.html.erb
<div class='clearfix dialog_link_to'>
  <div id='dialog_menu_left'>
    <span id='your_page_radio' class='radio<%= " selected_radio" if @page_area_selected %>'>
      <input type='radio' name='link_to' value='your_page' id='link_to_your_page' <%= "checked='true'" if @page_area_selected %> />
      <label for='link_to_your_page' class='stripped'><%= t('.your_page.tab_name') %></label>
    </span>
    <span id='web_address_radio' class='radio<%= " selected_radio" if @web_address_area_selected %>'>
      <input type='radio' name='link_to' value='web_address' id='link_to_web_address' <%= "checked='true'" if @web_address_area_selected %> />
      <label for='link_to_web_address' class='stripped'><%= t('.web_address.tab_name') %></label>
    </span>

    <span id='email_address_radio' class='radio<%= " selected_radio" if @email_address_area_selected %>'>
      <input type='radio' name='link_to' value='email_address' id='link_to_email_address' <%= "checked='true'" if @email_address_area_selected %> />
      <label for='link_to_email_address' class='stripped'><%= t('.email_address.tab_name') %></label>
    </span>
    <span id="resource_file_radio" class="radio<%= " selected_radio" if @resource_area_selected %>">
      <input type="radio" name="link_to" value="resource_file" id="link_to_resource_file" <%= "checked='true'" if @resource_area_selected %> />
      <label for="link_to_resource_file" class="stripped"><%= t('.your_resource.tab_name') %></label>
    </span>
  </div>

  <div id='dialog_main'>
    <div id='your_page_area' class='dialog_area' <%= "style='display: none'" unless @page_area_selected %>>
      <input type='hidden' name='selected_image' id='selected_image' />
      <div id='your_page_content' class='clearfix'>
        <div id='pages_list'>
          <ul class="link_list">
            <%= render :partial => "page_link", :collection => @pages,
                       :locals => {:child => 0} %>
          </ul>
          <%= will_paginate @pages,
                            :param_name => :page,
                            :renderer => Refinery::LinkRenderer,
                            :id => 'pages_paginate' %>
        </div>
      </div>
    </div>
    <div id='web_address_area' <%= "style='display: none'" unless @web_address_area_selected %> class='dialog_area'>
      <div id='web_address_content'>
        <label for='web_address_text'><%= t('.web_address.location') %></label>
        <%= text_field :web_address, :text, :value => @web_address_text, :style => "width: 70%" %>

        <label><%=t('.web_address.new_window') %></label>
        <input type='checkbox' name='web_address_target_blank' id='web_address_target_blank' <%= "checked='checked'" if @web_address_target_blank %> />
        <label for='web_address_target_blank' class='stripped'><%=t('.web_address.new_window_label') %></label>
        <p>
          <strong><%=t('.web_address.not_sure')%></strong>
        </p>
        <ol>
          <li><%=t('.web_address.step1')%></li>
          <li><%=t('.web_address.step2')%></li>
        </ol>
      </div>
    </div>
    <div id='email_address_area' <%= "style='display: none'" unless @email_address_area_selected %> class='dialog_area'>
      <div id='email_address_content'>
        <div class='field'>
          <label for='email_address_text'><%=t('.email_address.tab_name')%></label>
          <%= text_field :email_address, :text, :value => @email_address_text, :style => "width: 70%"%>
          <img id='email_address_test_loader' src='/lib/refinerycms/core/public/images/refinery/ajax-loader.gif' alt='Testing...' style='display: none;'/>
          <span id='email_address_test_result'></span>
        </div>

        <div class='field'>
          <label for='email_default_subject_text'><%=t('.email_address.subject_line_optional')%></label>
          <%= text_field :email_default_subject, :text, :value => @email_default_subject_text, :style => "width: 70%" %>
        </div>

        <div class='field'>
          <label for='email_default_body_text'><%=t('.email_address.body_optional')%></label>
          <%= text_area :email_default_body, :text, :value => @email_default_body_text, :style => "width: 70%", :rows => '' %>
        </div>

        <p>
          <strong><%=t('.email_address.not_sure')%></strong>
        </p>
        <ol style='margin-top: 3px'>
          <li>
            <%= t('.email_address.step1_html') %>
          </li>
          <li>
            <%= t('.email_address.step2_html') %>
          </li>
          <li>
            <%= t('.email_address.step3_html') %>
          </li>
        </ol>
      </div>
    </div>
    <div id="resource_file_area"<%= " style='display:none'" unless @resource_area_selected %> class="dialog_area">
      <div id='pages_list'>
        <ul class="link_list">
          <% @resources.each do |resource| -%>
            <% resource_linked = (resource.url == params[:current_link]) unless params[:current_link].blank? %>
            <li<%= " class='linked'" if resource_linked %>>
              <%= link_to "#{resource.title}.#{resource.ext}", resource.url,
                          :title => t('.your_resource.link_to_this_resource'),
                          :rel => resource.title,
                          :class => "page_link #{resource.ext}" %>
            </li>
          <% end %>
        </ul>
        <%= will_paginate @resources,
                          :param_name => :resource_page,
                          :previous_label => '&laquo;',
                          :next_label => '&raquo;',
                          :renderer => Refinery::LinkRenderer,
                          :url => {:paginating => "resource_file"},
                          :id => 'resouces_paginate' %>
      </div>
    </div>
  </div>
  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => nil,
               :cancel_url => '',
               :submit_button_text => t('.insert'),
               :hide_cancel => false,
               :cancel_title => nil,
               :hide_delete => true
             } %>
</div>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      link_tester.init('<%= test_url_admin_pages_dialogs_url %>',
                       '<%= test_email_admin_pages_dialogs_url %>');
      link_dialog.init();

      $('.link_list a').click(function(e){
        e.preventDefault();
      });
    });
  </script>
<% end %>