resources/config/routes.rb
::Refinery::Application.routes.draw do

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :resources, :except => :show do
      collection do
        get :insert
      end
    end
  end

end

resources/app/models/resource.rb
class Resource < ActiveRecord::Base

  # What is the max resource size a user can upload
  MAX_SIZE_IN_MB = 50

  resource_accessor :file

  validates :file, :presence => { :message => I18n.t('file_specify_for_upload') },
                   :length   => { :maximum => MAX_SIZE_IN_MB.megabytes,
                                  :message => I18n.t('file_should_be_smaller_than_max_file_size',
                                                     :max_file_size => MAX_SIZE_IN_MB.megabytes) }

   # Docs for acts_as_indexed http://github.com/dougal/acts_as_indexed
   acts_as_indexed :fields => [:file_name, :title, :type_of_content]

  # when a dialog pops up with images, how many images per page should there be
  PAGES_PER_DIALOG = 12

  # when listing images out in the admin area, how many images should show per page
  PAGES_PER_ADMIN_INDEX = 20

  delegate :ext, :size, :mime_type, :url, :to => :file

  # How many images per page should be displayed?
  def self.per_page(dialog = false)
    dialog ? PAGES_PER_DIALOG : PAGES_PER_ADMIN_INDEX
  end

  # used for searching
  def type_of_content
    self.mime_type.split("/").join(" ")
  end

  # Returns a titleized version of the filename
  # my_file.pdf returns My File
  def title
    CGI::unescape(self.file_name.to_s).gsub(/\.\w+$/, '').titleize
  end

end

resources/app/controllers/admin/resources_controller.rb
class Admin::ResourcesController < Admin::BaseController

  crudify :resource, :order => "updated_at DESC"
  before_filter :init_dialog

  def new
    @resource = Resource.new if @resource.nil?

    @url_override = admin_resources_url(:dialog => from_dialog?)
  end

  def create
    @resources = []
    unless params[:resource].present? and params[:resource][:file].is_a?(Array)
      @resources << (@resource = Resource.create(params[:resource]))
    else
      params[:resource][:file].each do |resource|
        @resources << (@resource = Resource.create(:file => resource))
      end
    end

    unless params[:insert]
      if @resources.all?{|r| r.valid?}
        flash.notice = t('refinery.crudify.created', :what => "'#{@resources.collect{|r| r.title}.join("', '")}'")
        unless from_dialog?
          redirect_to :action => 'index'
        else
          render :text => "<script>parent.window.location = '#{admin_resources_url}';</script>"
        end
      else
        self.new # important for dialogs
        render :action => 'new'
      end
    else
      if @resources.all?{|r| r.valid?}
        @resource_id = @resource.id if @resource.persisted?
        @resource = nil
      end
      self.insert
    end
  end

  def index
    search_all_resources if searching?
    paginate_all_resources

    if RefinerySetting.find_or_set(:group_resources_by_date_uploaded, true)
      @grouped_resources = group_by_date(@resources)
    end
    render :layout => 'refinery/admin'
  end

  def insert
    self.new if @resource.nil?

    @url_override = admin_resources_url(:dialog => from_dialog?, :insert => true)

    if params[:conditions].present?
      extra_condition = params[:conditions].split(',')

      extra_condition[1] = true if extra_condition[1] == "true"
      extra_condition[1] = false if extra_condition[1] == "false"
      extra_condition[1] = nil if extra_condition[1] == "nil"
      paginate_resources({extra_condition[0].to_sym => extra_condition[1]})
    else
      paginate_resources
    end
    render :action => "insert"
  end

protected

  def init_dialog
    @app_dialog = params[:app_dialog].present?
    @field = params[:field]
    @update_resource = params[:update_resource]
    @update_text = params[:update_text]
    @thumbnail = params[:thumbnail]
    @callback = params[:callback]
    @conditions = params[:conditions]
    @current_link = params[:current_link]
  end

  def restrict_controller
    super unless action_name == 'insert'
  end

  def paginate_resources(conditions={})
    @resources = Resource.paginate   :page => (@paginate_page_number ||= params[:page]),
                                     :conditions => conditions,
                                     :order => 'created_at DESC',
                                     :per_page => Resource.per_page(from_dialog?)
  end

end

resources/app/views/admin/resources/_existing_resource.html.erb
<div id='existing_resource_area' class='dialog_area' <%= "style='display:none;'" if @resource.errors.any? %>>
  <input type='hidden' name='linked_resource' id='linked_resource' />
  <div id='existing_resource_area_content' class='clearfix'>
    <div id='pages_list'>
      <ul class='link_list'>
        <% @resources.each do |resource| -%>
          <% resource_linked = (resource.url == params[:current_link]) if params[:current_link].present? %>
          <li<%= " class='linked'" if resource_linked %>>
            <%= link_to "#{resource.title} (#{resource.file_name})", resource.url,
                        :title => t('.link_to_file'),
                        :rel => resource.title,
                        :class => 'page_link',
                        :id => "resource_#{resource.id}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => nil,
               :cancel_url => admin_resources_url,
               :submit_button_text => t('.button_text'),
               :hide_cancel => true,
               :hide_delete => true,
               :paginate => {
                 :collection => @resources,
                 :url => {:controller => "/admin/resources", :action => "insert", :dialog => from_dialog? }
               }
             } if @app_dialog or @resources.any? %>
</div>

resources/app/views/admin/resources/_form.html.erb
<%= form_for [:admin, @resource], :url => @url_override || @url,
                                  :html => {:multipart => true} do |f| -%>

  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => @resource,
               :include_object_name => false
             } %>

  <div class='field'>
    <% if action_name =~ /(edit)|(update)/ %>
      <%= link_to t('.download_current'), @resource.url,
                  :title => @resource.title %>
      <em><%= t('.or')%></em><%= t('.replace') %>
      <%= f.file_field :file %>
    <% else %>
      <% # we must only hint at multiple when it's a *new* record otherwise update fails. %>
      <%= f.file_field :file, :multiple => (true unless @resource.persisted?) %>
    <% end %>
  </div>

  <div class='field'>
    <label>
      <%= t('.maximum_file_size', :megabytes => Resource::MAX_SIZE_IN_MB) %>
    </label>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :hide_cancel => (@app_dialog or action_name == "insert" or from_dialog?),
               :delete_title => t('admin.resources.delete'),
               :delete_confirmation => (t('shared.admin.delete.message',
                                        :title => @resource.title) if @resource.persisted?)
             } %>

  <% if @app_dialog -%>
    <input type='hidden' name='app_dialog' value='<%= @app_dialog %>' />
    <input type='hidden' name='field' value='<%= @field %>' />
    <input type='hidden' name='update_resource' value='<%= @update_resource %>' />
    <input type='hidden' name='update_text' value='<%= @update_text %>' />
    <input type='hidden' name='thumbnail' value='<%= @thumbnail %>' />
    <input type='hidden' name='callback' value='<%= @callback %>' />
    <input type='hidden' name='conditions' value='<%= @conditions %>' />
    <input type='hidden' name='current_link' value='<%= @current_link %>' />
  <% end -%>
<% end -%>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      link_dialog.init();
    });
  </script>
<% end if from_dialog? %>

resources/app/views/admin/resources/_resource.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title <%= resource.ext %>'>
    <%= resource.title %>.<%= resource.ext %>
    <span class="preview">- <%= number_to_human_size(resource.size) %></span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('page_white_put.png'),  resource.url,
                :title => t('.download', :size => number_to_human_size(resource.size)) %>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_admin_resource_url(resource),
                :title => t('admin.resources.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), admin_resource_path(resource),
                :class => "cancel confirm-delete",
                :title => t('admin.resources.delete'),
                :confirm => t('shared.admin.delete.message', :title => resource.title),
                :method => :delete %>
  </span>
</li>

resources/app/views/admin/resources/edit.html.erb
<%= render :partial => "form" -%>

resources/app/views/admin/resources/index.html.erb
<div id='records' class='files'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
  <% end %>
  <% if @resources.any? %>
    <%= will_paginate @resources %>
    <% unless searching? or !RefinerySetting.find_or_set(:group_resources_by_date_uploaded, true)
        @grouped_resources.each do |container|
          date = Date.parse((resource_group = container.last).first.created_at.to_s)
        %>
          <h3><%= l(date, :format => :long ) %></h3>
          <ul>
            <%= render :partial => "resource", :collection => resource_group %>
          </ul>
        <% end %>
    <% else %>
      <ul>
        <%= render :partial => "resource", :collection => @resources %>
      </ul>
    <% end %>
    <%= will_paginate @resources %>
  <% else %>
    <p>
      <% unless searching? %>
        <strong><%= t('.no_files_yet') %></strong>
      <% else %>
        <%= t('shared.admin.search.no_results') %>
      <% end %>
    </p>
  <% end %>
</div>
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => admin_resources_url} %>
    </li>
    <li>
      <%= link_to t('.upload_new'), new_admin_resource_url(:dialog => true,
                                                           :width => 600,
                                                           :height => 300),
                  :class => "add_icon" %>
    </li>
  </ul>
</div>

resources/app/views/admin/resources/insert.html.erb
<% user_can_modify_resources = Refinery::Plugins.active.names.include?("refinery_files") %>
<div class='clearfix'>
  <div id='dialog_menu_left'>
    <% if (any_resources = @resources.any?) %>
      <span id='existing_resource_radio' class='radio<%= " selected_radio" if @resource.errors.empty? %>'>
        <input type='radio' name='resource_type' value='existing_resource' id='resource_type_existing' <%= "checked='true'" if @resource.errors.empty? %> />
        <label for='resource_type_existing' class='stripped'>
          <%= t('.existing') %>
        </label>
      </span>
    <% end %>
    <% if user_can_modify_resources %>
      <span id='upload_resource_radio' class='radio<%= " selected_radio" if @resource.errors.any? or @resources.empty? %>'>
        <input type='radio' name='resource_type' value='upload_resource' id='resource_type_upload' <%= "checked='true'" if @resources.empty? or @resource.errors.any? %> />
        <label for='resource_type_upload' class='stripped'>
          <%= t('.new') %>
        </label>
      </span>
    <% end %>
  </div>

  <div id='dialog_main'>
    <% if any_resources or user_can_modify_resources %>
      <%= render :partial => 'existing_resource' if any_resources %>

      <% if user_can_modify_resources %>
        <div id='upload_resource_area' class='dialog_area' <%= "style='display:none;'" if any_resources and @resource.errors.empty? %>>
          <%= render :partial => "form", :locals => {:insert => true} %>
        </div>
      <% end %>
    <% else %>
      <% flash.now[:error] = t('.no_files') %>
      <%= render :partial => "/shared/admin/form_actions",
                 :locals => {
                   :f => nil,
                   :cancel_url => '',
                   :hide_cancel => false,
                   :hide_delete => true,
                   :hide_submit => true,
                   :cancel_button_text => t('shared.admin.form_actions.close'),
                   :cancel_title => nil
                 } %>
    <% end %>
  </div>
</div>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      link_dialog.init();
      resource_picker.init(<%= @callback.present? ? "self.parent.#{@callback}" : "null" %>);
    });
  </script>
<% end %>

resources/app/views/admin/resources/new.html.erb
<%= render :partial => "form" -%>